# Generated by cucumber-sinatra. (2013-05-07 14:22:58 +0100)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'lib/collaborator.rb')

require 'capybara'
require 'capybara/cucumber'
require 'capybara-webkit'
require 'rspec'
require 'rack/test'

Capybara.app = Collaborator
Capybara.javascript_driver = :webkit

class CollaboratorWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

Mongoid.logger = nil

World do
  CollaboratorWorld.new
end
